export enum EAllStat {
  atkFlt = 'atkFlt',
  atkPer = 'atkPer',
  basicDmgPer = 'basicDmgPer',
  breakEff = 'breakEff',
  critDmg = 'critDmg',
  critRate = 'critRate',
  defFlt = 'defFlt',
  defPer = 'defPer',
  dmgPer = 'dmgPer',
  ehr = 'ehr',
  energyReg = 'energyReg',
  followUpDmgPer = 'followUpDmgPer',
  hpFlt = 'hpFlt',
  hpPer = 'hpPer',
  skillDmgPer = 'skillDmgPer',
  spdFlt = 'spdFlt',
  ultDmgPer = 'ultDmgPer',
}
